### ISSUE TITLE
Broken PDF: Cannot read property 'fantasy-land/reduce' of undefined

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#157]
URL: http://localhost:3007/2019/08/30/die-credit-suisse-und-die-geheimen-schulden-von-mocambique

```
(node:12422) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fantasy-land/reduce' of undefined
    at _reduce (/Users/thomas/Code/pdf/node_modules/ramda/src/internal/_reduce.js:47:18)
    at /Users/thomas/Code/pdf/node_modules/ramda/src/internal/_curry3.js:32:18
    at f1 (/Users/thomas/Code/pdf/node_modules/ramda/src/internal/_curry1.js:18:17)
    at /Users/thomas/Code/pdf/node_modules/ramda/src/internal/_pipe.js:3:14
    at /Users/thomas/Code/pdf/node_modules/ramda/src/internal/_arity.js:10:19
    at /Users/thomas/Code/pdf/node_modules/@react-pdf/textkit/lib/engines/textDecoration/index.js:150:43
    at /Users/thomas/Code/pdf/node_modules/ramda/src/internal/_pipe.js:3:14
    at /Users/thomas/Code/pdf/node_modules/ramda/src/internal/_arity.js:10:19
    at /Users/thomas/Code/pdf/node_modules/@react-pdf/textkit/lib/layout/finalizeFragments.js:98:123
    at args.<computed> (/Users/thomas/Code/pdf/node_modules/ramda/src/addIndex.js:40:27)
```

**Comment by tpreusse** [comment]
It's a new bug that only happens after bumping `@react-pdf/renderer` to v2.

**Comment by tpreusse** [comment]
Issue seems to be related to the `Link` component. Removing it resolves the error. Just removing the styles does not help.
```diff
diff --git a/src/components/Anchor.js b/src/components/Anchor.js
index e2fb303..aabb237 100644
--- a/src/components/Anchor.js
+++ b/src/components/Anchor.js
@@ -10,17 +10,8 @@ const styles = StyleSheet.create({
   }
 })
 
-const Anchor = ({ children, href }) => (
-  <Link
-    style={styles.link}
-    src={
-      href && href[0] === '/' // path urls
-        ? FRONTEND_BASE_URL + href
-        : href
-    }
-  >
-    {children}
-  </Link>
-)
+const Anchor = ({ children, href }) => {
+  return children
+}
 
 export default Anchor
 ```

**Comment by tpreusse** [comment]
Isolated the issue:
```json
{
  "children": [
    {
      "type": "text",
      "value": "­Privinvest"
    }
  ],
  "type": "link",
  "title": null,
  "url": "https://www.privinvest.com/"
}
```

This link has a invisible soft hyphen at the start:
<img width="541" alt="Screenshot 2021-06-30 at 14 02 56" src="https://user-images.githubusercontent.com/410211/123957286-e3d5b280-d9ab-11eb-966f-78ff0816082e.png">

Leading to our hyphenation function return this:
```json
["", "Privinvest"]
```

Which then causes an explosion in the react pdf text engine.

Fix in our hyphenationCallback:
```diff
diff --git a/src/lib/hyphenation.js b/src/lib/hyphenation.js
index 65283a9..2459dd4 100644
--- a/src/lib/hyphenation.js
+++ b/src/lib/hyphenation.js
@@ -7,7 +7,7 @@ const hypenator = createHyphenator(patterns)
 
 const hyphenate = (string) => {
   if (string.includes(SOFT_HYPHEN)) {
-    return string.split(SOFT_HYPHEN)
+    return string.split(SOFT_HYPHEN).filter(Boolean)
   }
 
   return hypenator(string).split(SOFT_HYPHEN)
```
