### ISSUE TITLE
ReferenceError: secondEnd is not defined

### ISSUE THREAD

**Issue by diegomura** [orbiting/pdf#64]
example: http://localhost:3007/2018/04/24/die-haben-die-demokratie-kaputtgemacht

The issue seems to be on `textkit's TextDecorationEngine`

**Comment by tpreusse** [comment]
a second error
env
```
API_URL=https://api.republik.love/graphql
FRONTEND_BASE_URL=https://republik.love
ASSETS_SERVER_BASE_URL=https://cdn.republik.pink
```
http://localhost:3007/2018/04/16/pdf-fixture.pdf

```
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of undefined
    at GlyphString.get end [as end] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:43:66)
    at GlyphString.get length [as length] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:53:17)
    at GlyphString.get glyphRuns [as glyphRuns] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:78:56)
    at GlyphString.get height [as height] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:61:17)
    at LayoutEngine.layoutParagraph (/app/node_modules/@react-pdf/textkit/dist/layout/LayoutEngine.js:109:139)
    at LayoutEngine.layoutColumn (/app/node_modules/@react-pdf/textkit/dist/layout/LayoutEngine.js:82:26)
    at LayoutEngine.layout (/app/node_modules/@react-pdf/textkit/dist/layout/LayoutEngine.js:68:22)
    at TextEngine.layout (/app/node_modules/@react-pdf/core/lib/elements/TextEngine.js:114:25)
    at Text.measureText (/app/node_modules/@react-pdf/core/lib/elements/Text.js:70:21)
    at /app/node_modules/yoga-layout/dist/entry-common.js:221:40

```

**Comment by tpreusse** [comment]
additional examples: /2018/04/21/das-grosse-baz-erfolgsgeheimnis.pdf (prd env)

**Comment by diegomura** [comment]
I moved the second issue to https://github.com/orbiting/pdf/issues/71 to separate concerns. 
This one is fixed in https://github.com/devongovett/textkit/commit/5aecbe9174152b02459149f1bcd7190db90f2b08
