### ISSUE TITLE
TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by diegomura** [orbiting/pdf#71]
env

```
API_URL=https://api.republik.love/graphql
FRONTEND_BASE_URL=https://republik.love
ASSETS_SERVER_BASE_URL=https://cdn.republik.pink
```

http://localhost:3007/2018/04/16/pdf-fixture.pdf

```
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of undefined
    at GlyphString.get end [as end] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:43:66)
    at GlyphString.get length [as length] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:53:17)
    at GlyphString.get glyphRuns [as glyphRuns] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:78:56)
    at GlyphString.get height [as height] (/app/node_modules/@react-pdf/textkit/dist/models/GlyphString.js:61:17)
    at LayoutEngine.layoutParagraph (/app/node_modules/@react-pdf/textkit/dist/layout/LayoutEngine.js:109:139)
    at LayoutEngine.layoutColumn (/app/node_modules/@react-pdf/textkit/dist/layout/LayoutEngine.js:82:26)
    at LayoutEngine.layout (/app/node_modules/@react-pdf/textkit/dist/layout/LayoutEngine.js:68:22)
    at TextEngine.layout (/app/node_modules/@react-pdf/core/lib/elements/TextEngine.js:114:25)
    at Text.measureText (/app/node_modules/@react-pdf/core/lib/elements/Text.js:70:21)
    at /app/node_modules/yoga-layout/dist/entry-common.js:221:40
```

Reported by @tpreusse in #64

**Comment by diegomura** [comment]
**Cause:** Text fails to render
```
'republik.ch v1.0 is online, running and stable.\n\nIt took 2 companies, scaling from 9 to 41 people and around four thousand contributions over 11 month from my side (https://t.co/bB4I8KbOTn metric).\n\nVery happy about this, such a great team and incredible opportunity. https://t.co/h6kFTyMJFC'
```
**Reason:** textkit does not support empty lines, which are caused by the double `\n`

**Comment by tpreusse** [comment]
seems to always happen in tweets. Workaround: strip double `\n`?

**Comment by diegomura** [comment]
Yes. That's a valid workaround, but textkit should be able to render empty new lines. I actually was able to do it. Now I'm integrating it into react-pdf
